<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>fm.framework</groupId>
  <artifactId>SeleniumAutomation</artifactId>
  <version>1.0.0</version>
  <packaging>jar</packaging>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <!-- by default runMode is local and value is cucumber.tag = @smoke -->
    <runMode>local</runMode>
    <!-- mvn test -Dtags="@smoke" , mvn test -DrunMode="local"  pass as String Value-->
    <tags>@smoke</tags>
    <runner>JunitRunner</runner>
    <maven.surefire.plugin.version>3.5.6</maven.surefire.plugin.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.piyush</groupId>
      <artifactId>core</artifactId>
      <version>1.0.8</version>
    </dependency>
  </dependencies>

<build>
  <plugins>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-surefire-plugin</artifactId>
      <version>${maven.surefire.plugin.version}</version>
      <configuration>
        <!-- Module-specific test runner inclusion here you can run any runner -->
        <includes>
          <include>**/${runner}.java</include>
        </includes>
        <systemPropertyVariables>
          <!-- This pass the System Variable into JVm Directly you fetch it Framework  -->
          <!-- mvn test -Dcucumber.tags=@Smoke -->
          <cucumber.filter.tags>${tags}</cucumber.filter.tags>
          <runMode>${runMode}</runMode>
        </systemPropertyVariables>
      </configuration>
    </plugin>
  </plugins>
</build>
</project>
