# This JUnit Platform properties used to control the Junit-5 with Cucumber

# cucumber-junit-platform-engine this need to in POM XML But Always Run Parallel Execution through Cucumber not by JUnit
# Step definitions package
cucumber.glue = com.example.stepdefinitions

# Location of feature files
cucumber.features = src/test/resources/features

# Tag filtering (e.g. run smoke tests, skip ignored)
cucumber.filter.tags = @smoke and not @ignored
# Serenity / Cucumber Reporter Plugins
cucumber.plugin = io.cucumber.core.plugin.SerenityReporterParallel, pretty

# Enable parallel execution via Cucumber engine false or true (Parallel scenario execution inside Cucumber)
cucumber.execution.parallel.enabled = true

# Choose thread count strategy: 'fixed' or 'dynamic'
cucumber.execution.parallel.config.strategy = fixed
cucumber.execution.parallel.config.fixed.parallelism = 4


